name: gotask
description: "To-Do list"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  supabase_flutter: ^2.0.2
  google_fonts: ^6.1.0
  email_validator: ^2.1.17
  uuid: ^4.0.0
  encrypt: ^5.0.3
  flutter_sliding_up_panel: ^2.1.1
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true